import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <iframe src="https://www.google.com/maps/embed?pb=!1m28!1m12!1m3!1d96743.25988892588!2d-74.16163504463654!3d40.735033160790664!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!4m13!3e3!4m5!1s0x89c252e1c5ec0cef%3A0xb3f3b437c5d7f286!2sAeropuerto%20Internacional%20Libertad%20de%20Newark%2C%203%20Brewster%20Rd%2C%20Newark%2C%20NJ%2007114!3m2!1d40.6895314!2d-74.1744624!4m5!1s0x89c259ae15b2adcb%3A0x7955420634fd7eba!2sPenn%20Station%2C%20Nueva%20York!3m2!1d40.750568!2d-73.99351899999999!5e0!3m2!1ses-419!2sus!4v1640373085211!5m2!1ses-419!2sus" width="800" height="600" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
